### ISSUE TITLE
Possible to add kRenderFxGlowShell on view model?

### ISSUE THREAD

**Issue by z0h1r-LK** [CS-NextClient/NextClientServerApi#7]
Hi, That's possible to set `kRenderFxGlowShell` on view model or can add an API in future.
I've seen it in Mod on ModDB
We want an example like this :
```pawn
ncl_viewmodel_set_rendering(id, kRenderFxGlowShell, 255, 0, 0, kRenderNormal, 16)
```
:3

**Comment by Psycrow101** [comment]
@z0h1r-LK https://github.com/CS-NextClient/NextClientServerApi/blob/main/addons/amxmodx/scripting/include/next_client_api.inc#L201
